openapi: 3.0.0
info:
  title: Sample API
  description: API documentation for Sample API.
  version: 1.0.0
paths:
  /sample:
    get:
      summary: Sample endpoint
      responses:
        '200':
          description: A successful response
components:
  schemas:
    Sample:
      type: object
      properties:
        id:
          type: integer
          example: 1
